backend:
  name: git-gateway
  branch: master # Branch to update (master by default)
  squash_merges: true

# This line should *not* be indented
# publish_mode: editorial_workflow

media_folder: "assets/images/posts" # Folder where user uploaded files should go
site_url: https://showcase.rotaract3190.org/
display_url: showcase.rotaract3190.org

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{date}}-{{slug}}" # {{year}}-{{month}}-{{day}}-{{slug}}
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - label: "Host Club"
        name: "author"
        widget: "select"
        options:
          - { label: "Bangalore Southwest", value: "rcbsw" }
          - { label: "Gems B School", value: "rcgems" }
          - { label: "Bangalore", value: "rcb" }
          - { label: "K.G.F. Community", value: "rckgf" }
          - { label: "Bangalore B.I.T", value: "rcbit" }
          - { label: "Surana College", value: "rcsurana" }
          - { label: "SBMJC KGF", value: "rcsbmjc-kgf" }
          - { label: "PES University", value: "rcpes" }
          - { label: "BMS Yelahanka", value: "rcbmsylk" }
          - { label: "C M R I T", value: "rccmrit" }
          - { label: "Nagarjuna Degree College", value: "rcnagarjuna" }
          - { label: "Bangalore West", value: "rbw" }
          - { label: "Bangalore South Parade", value: "rcsouthparade" }
          - { label: "Rotary Club of KGF", value: "rotarykgf" }
          - { label: "Bangalore Golden Rock", value: "rcgoldenrock" }
          - { label: "Chandapur Rupashi RID 3282", value: "rcchandapurrupashi" }
          - { label: "OPJU, Sonepat", value: "rcopju" }
          - { label: "Bangalore Vijayanagar", value: "rbv" }
          - { label: "KSSEM", value: "rckssem" }
          - { label: "Yelahanka", value: "rcylk" }
          - { label: "MES College", value: "rcmes" }
          - { label: "Bangalore Junction", value: "rcjunction" }
          - { label: "Presidency College", value: "rcpc" }
          - { label: "Vidyaranyapura", value: "rcvidyaranyapura" }
          - { label: "Bangalore Indiranagar", value: "rbi" }
          - { label: "Delhi Akash", value: "rcdelhiakash" }
          - { label: "Marathahalli", value: "rcm" }
          - { label: "Alexandria and Cairo", value: "rcalexandriacairo" }
          - { label: "Koramangala", value: "rck" }
          - { label: "Rotary Bangalore Junction", value: "rotaryjunction" }
          - { label: "Welingkar Bangalore", value: "rcwelingkar" }
          - { label: "Rotary Club of Vidyaranyapura", value: "rotaryvidyaranyapura" }
      - label: "Tags/Partner Clubs"
        name: "tags"
        widget: "select"
        multiple: true
        options:
          - { label: "Bangalore Southwest", value: "rcbsw" }
          - { label: "Gems B School", value: "rcgems" }
          - { label: "Bangalore", value: "rcb" }
          - { label: "K.G.F. Community", value: "rckgf" }
          - { label: "Bangalore B.I.T", value: "rcbit" }
          - { label: "Surana College", value: "rcsurana" }
          - { label: "SBMJC KGF", value: "rcsbmjc-kgf" }
          - { label: "PES University", value: "rcpes" }
          - { label: "BMS Yelahanka", value: "rcbmsylk" }
          - { label: "C M R I T", value: "rccmrit" }
          - { label: "Nagarjuna Degree College", value: "rcnagarjuna" }
          - { label: "Bangalore West", value: "rbw" }
          - { label: "Bangalore South Parade", value: "rcsouthparade" }
          - { label: "Rotary Club of KGF", value: "rotarykgf" }
          - { label: "Bangalore Golden Rock", value: "rcgoldenrock" }
          - { label: "Chandapur Rupashi RID 3282", value: "rcchandapurrupashi" }
          - { label: "OPJU, Sonepat", value: "rcopju" }
          - { label: "Bangalore Vijayanagar", value: "rbv" }
          - { label: "KSSEM", value: "rckssem" }
          - { label: "Yelahanka", value: "rcylk" }
          - { label: "MES College", value: "rcmes" }
          - { label: "Bangalore Junction", value: "rcjunction" }
          - { label: "Presidency College", value: "rcpc" }
          - { label: "Vidyaranyapura", value: "rcvidyaranyapura" }
          - { label: "Bangalore Indiranagar", value: "rbi" }
          - { label: "Delhi Akash", value: "rcdelhiakash" }
          - { label: "Marathahalli", value: "rcm" }
          - { label: "Alexandria and Cairo", value: "rcalexandriacairo" }
          - { label: "Koramangala", value: "rck" }
          - { label: "Rotary Bangalore Junction", value: "rotaryjunction" }
          - { label: "Welingkar Bangalore", value: "rcwelingkar" }
          - { label: "Rotary Club of Vidyaranyapura", value: "rotaryvidyaranyapura" }
      - {label: "Description", name: "description", widget: "markdown"}
      - label: "Avenues"
        name: "categories"
        widget: "select"
        multiple: true
        options: ["Club-Service", "Community-Service", "International-Service", "Professional-Service"]
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Featured?", name: "featured", widget: "boolean", default: false}
      - {label: "Hidden?", name: "hidden", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}
